# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queue',
            new_name='Window1Queue',
        ),
    ]
