# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilename',
            new_name='profile',
        ),
    ]
