# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170527_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
